-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.department
(

    CONSTRAINT department_pkey PRIMARY KEY (depart_id),
    CONSTRAINT depart_city_unique UNIQUE (depart_name, depart_city)
);

CREATE TABLE IF NOT EXISTS public.employees
(

    CONSTRAINT employees_pkey PRIMARY KEY (emp_id),
    CONSTRAINT emp_details_unique UNIQUE (emp_id, email, salary_id, overtime_id)
);

CREATE TABLE IF NOT EXISTS public.overtime_hours
(

    CONSTRAINT overtime_id_pkey PRIMARY KEY (overtime_id),
    CONSTRAINT overtime_unique UNIQUE (overtime_id)
        INCLUDE(overtime_hours)
);

CREATE TABLE IF NOT EXISTS public.roles
(

    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.salaries
(

    CONSTRAINT salaries_pkey PRIMARY KEY (salary_id)
);



ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_depart_id_fkey FOREIGN KEY (depart_id)
    REFERENCES public.department (depart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_overtime_id_fkey FOREIGN KEY (overtime_id)
    REFERENCES public.overtime_hours (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_salary_id_fkey FOREIGN KEY (salary_id)
    REFERENCES public.salaries (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;

-------------------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO employees
VALUES
	('1', 'Joe', 'Johnson', 'M', '29 Browning Road, Observatory, Cape Town, 7925', 'jshezi@outlook.com', 2, 4, 3 ),
	('3', 'Brian', 'Becker', 'M', '44 Shakespeare Road, Matlosana, Orkney, 2619', 'brianbekker@outlook.com', 5, 1, 1 ),
	('4', 'Paula', 'Peterson', 'F', '7 Marshall Road, Humewood, Pretoria, 0001', 'ppeter@gmail.com', 4, 3, 4 );
INSERT INTO employees
VALUES	
	('2', 'Makhosi', 'Mshengu', 'F', '67 Carey Road, Pelham, Pietermaritzburg, 3201', 'mmshengu@yahoo.co.za', 1, 5, 5, 1),
	('5', 'Olivia' ,'Oaks', 'F', '1 Albion Road, Rondebosch Oaks, Rondebosch, Cape Town, 7701', 'olioaks@yahoo.com', 2, 2, 2, 2);
	
	

INSERT INTO department 
VALUES 
	('1', 'Department of Education', 'Pietermaritzburg'),
	('2', 'Department of Water and Sanitation', 'Cape Town'),
	('3', 'Department of Agriculture, Forestry and Fisheries', 'Port Elizabeth'),
	('4', 'Department of Home Affairs', 'Pretoria'),
	('5', 'Department of Minerals and Energy', 'Orkney');



INSERT INTO roles
VALUES
	('1', 'Land Surveyor'),
	('2', 'Administrative Clerk'),
	('3', 'Data Center Technician'),
	('4', 'Environmental Manager'),
	('5', 'Teachers Assistant');



INSERT INTO salaries 
VALUES
	('1', '390000'),
	('2', '159115'),
	('3', '273752'),
	('4', '480000'),
	('5', '132000');




INSERT INTO overtime_hours
VALUES
	('1', '09:00:50'),
	('2', '15:30:00');



-- JOINING TABLES
SELECT * FROM employees;
SELECT * FROM department;
SELECT * FROM roles;
SELECT * FROM salaries;
SELECT * FROM overtime_hours;

SELECT 
	employees.emp_id, 
	employees.first_name,
	employees.surname,
	employees.email,
	department.depart_name,
	roles.emp_role,
	salaries.salary_pa,
	overtime_hours.overtime_hours
FROM employees 
	LEFT JOIN department ON employees.depart_id = department.depart_id 
	LEFT JOIN roles ON employees.role_id = roles.role_id
	LEFT JOIN salaries ON employees.salary_id = salaries.salary_id
	LEFT JOIN overtime_hours ON employees.overtime_id = overtime_hours.overtime_id




-- Showing that constraints are working
-- Testing Primary Key Constraint
INSERT INTO employees
VALUES
	('1', 'Joe', 'Jackson', 'M', '29 Scott Road, Rondebosch, Cape Town, 7925', 'jjackson@gmail.com', 2, 4, 3 );
--RETURNS ERROR:  Key (emp_id)=(1) already exists.duplicate key value violates unique constraint "employees_pkey" 



-- Testing Foreign Key Constraint
INSERT INTO employees
VALUES
	(6, 'Joe', 'Jackson', 'M', '29 Scott Road, Rondebosch, Cape Town, 7925', 'jjackson@gmail.com', 6, 4, 3)
--RETURNS ERROR:  Key (depart_id)=(6) is not present in table "department".insert or update on table "employees" violates foreign key constraint "employees_depart_id_fkey" 
